CREATE DATABASE IF NOT EXISTS Kegums;

USE Kegums;

CREATE TABLE IF NOT EXISTS kegs (
  id INT AUTO_INCREMENT KEY,
  name VARCHAR(48) NOT NULL,
  volume FLOAT NOT NULL DEFAULT 661,
  tapped TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  kicked TIMESTAMP NULL,
  bannerId INT NULL
);

CREATE TABLE IF NOT EXISTS pours (
  id INT AUTO_INCREMENT KEY,
  kegId INT NOT NULL,
  volume FLOAT NOT NULL,
  start TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  end TIMESTAMP NULL,
  INDEX(`kegId`)
);

CREATE TABLE IF NOT EXISTS temperature (
  id INT AUTO_INCREMENT KEY,
  degrees FLOAT NOT NULL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS banners (
  id INT AUTO_INCREMENT KEY,
  url VARCHAR(128) NOT NULL
);

# Schema v1.1
CREATE TABLE IF NOT EXISTS drinkers (
  id INT AUTO_INCREMENT KEY,
  name VARCHAR(48) NOT NULL
);

CREATE TABLE IF NOT EXISTS drinking (
  drinkerId INT NULL,
  CONSTRAINT drinking_drinker_pk
    FOREIGN KEY (drinkerId)
    REFERENCES drinkers(id)
);

ALTER TABLE pours
  DROP COLUMN end,
  ADD drinkerId INT
;

INSERT INTO drinking (drinkerId) values (NULL);

ALTER TABLE pours
  ADD CONSTRAINT pour_drinker_fk
    FOREIGN KEY(drinkerId)
    REFERENCES drinkers(id)
;

ALTER TABLE kegs
  DROP COLUMN bannerId
;

DROP TABLE banners;

ALTER TABLE kegs
  ADD price DECIMAL(6,2)
;

UPDATE kegs SET price = 86;
