CREATE DATABASE IF NOT EXISTS Kegums;

USE Kegums;

CREATE TABLE kegs (
  id INT AUTO_INCREMENT KEY,
  name VARCHAR(48) NOT NULL,
  volume FLOAT NOT NULL DEFAULT 661,
  tapped TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  kicked TIMESTAMP NULL,
  bannerId INT NULL
);

CREATE TABLE pours (
  id INT AUTO_INCREMENT KEY,
  kegId INT NOT NULL,
  volume FLOAT NOT NULL,
  start TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  end TIMESTAMP NULL,
  INDEX(`kegId`)
);

CREATE TABLE banners (
  id INT AUTO_INCREMENT KEY,
  url VARCHAR(128) NOT NULL
);  

CREATE TABLE temperature (
  id INT AUTO_INCREMENT KEY,
  degrees FLOAT NOT NULL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP  
);

