CREATE DATABASE IF NOT EXISTS Kegums;

USE Kegums;

CREATE TABLE kegs (
  id INT AUTO_INCREMENT KEY,
  name VARCHAR(48) NOT NULL,
  volume FLOAT NOT NULL DEFAULT 661,
  tapped TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  kicked TIMESTAMP NULL,
  bannerId INT NULL
);

CREATE TABLE pours (
  id INT AUTO_INCREMENT KEY,
  kegId INT NOT NULL,
  volume FLOAT NOT NULL,
  start TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  end TIMESTAMP NULL,
  INDEX(`kegId`)
);

CREATE TABLE banners (
  id INT AUTO_INCREMENT KEY,
  url VARCHAR(128) NOT NULL
);

CREATE TABLE temperature (
  id INT AUTO_INCREMENT KEY,
  degrees FLOAT NOT NULL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

# Schema v1.1
CREATE TABLE drinkers (
  id INT AUTO_INCREMENT KEY,
  name VARCHAR(48) NOT NULL
);

CREATE TABLE drinking (
  drinkerId INT NULL,
  CONSTRAINT drinking_drinker_pk
    FOREIGN KEY (drinkerId)
    REFERENCES drinkers(id)
);

ALTER TABLE pours
  DROP COLUMN end,
  ADD drinkerId INT
;

INSERT INTO drinking (drinkerId) values (NULL);

ALTER TABLE pours
  ADD CONSTRAINT pour_drinker_fk
    FOREIGN KEY(drinkerId)
    REFERENCES drinkers(id)
;
